import { useRef, useState } from "react";
import useBatches from "../../utils/useBatches";
import { teacherId, teacherBatches } from "../../utils/batchStorage";
import PublicIcon from "../../components/PublicIcon";
import "./RecordingsNotes.css";
export default function RecordingsNotes() {
 const state=useBatches();
 const batches=teacherBatches(state);
 const materials=state.materials.filter(item=>item.teacherId===teacherId && batches.some(batch=>batch.id===item.batchId && batch.courseId===item.courseId));
 const [search,setSearch]=useState("");const [course,setCourse]=useState("");const [tab,setTab]=useState("recordings");const [selected,setSelected]=useState(null);const dialog=useRef(null);
 const groups={recordings:materials.filter(item=>item.type==="Recording / Notes"),notes:materials.filter(item=>/notes/i.test(item.type)),materials:materials.filter(item=>item.type!=="Recording / Notes")};
 const visible=groups[tab].filter(item=>(!course || item.course===course) && `${item.title} ${item.course} ${item.batch}`.toLowerCase().includes(search.trim().toLowerCase()));
 return <section className="trn-page"><header><h1>Recordings &amp; Notes</h1><p>Access class recordings, notes and shared materials from your assigned batches.</p></header><div className="trn-stats">{[[groups.recordings.length,"Recordings","play"],[groups.notes.length,"Notes","book"],[groups.materials.length,"Learning Materials","layers"]].map(([value,label,icon])=><article key={label}><span><PublicIcon name={icon}/></span><div><strong>{value}</strong><p>{label}</p></div></article>)}</div><div className="trn-tools"><nav aria-label="Material type">{[["recordings","All Recordings"],["notes","Notes"],["materials","Shared Materials"]].map(([value,label])=><button key={value} aria-pressed={tab===value} onClick={()=>setTab(value)}>{label}</button>)}</nav><select aria-label="Course" value={course} onChange={e=>setCourse(e.target.value)}><option value="">All Courses</option>{[...new Set(materials.map(item=>item.course))].map(value=><option key={value}>{value}</option>)}</select><input aria-label="Search recordings and notes" placeholder="Search recordings, notes..." value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="trn-list">{visible.map(item=><article key={item.id}><div className="trn-thumbnail"><PublicIcon name={tab==="recordings" ? "play" : "book"}/><small>{item.duration || item.type}</small></div><div className="trn-info"><h2>{item.title}</h2><p>{item.course} ? {item.batch}</p><small>{item.date || "Date not recorded"}{item.lecture ? ` ? ${item.lecture}` : ""}</small></div><span className="trn-status">{item.status}</span><button onClick={()=>{setSelected(item);dialog.current.showModal();}}>View Details</button></article>)}{!visible.length && <p className="trn-empty">No matching materials in your assigned batches.</p>}</div><footer>Showing {visible.length} items</footer><dialog ref={dialog} aria-labelledby="trn-title"><h2 id="trn-title">{selected?.title}</h2>{selected && <dl>{[["Course",selected.course],["Batch",selected.batch],["Type",selected.type],["Status",selected.status],["Date",selected.date],["Duration",selected.duration]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value || "Not provided"}</dd></div>)}</dl>}<p>Recording playback and file downloads require an attached file.</p><form method="dialog"><button>Close</button></form></dialog></section>;
}
