import { Link } from "react-router-dom";
import useBatches from "../../utils/useBatches";
import useCourses from "../../utils/useCourses";
import { teacherStudents, teacherCourses } from "../../utils/batchStorage";
import PublicIcon from "../../components/PublicIcon";
import "./StudentProgress.css";
const average = rows => rows.length ? Math.round(rows.reduce((sum,row)=>sum+row.progress,0)/rows.length) : 0;
export default function StudentProgress() {
 const students=teacherStudents(useBatches());
 const courses=teacherCourses(useCourses());
 const lower=students.filter(student=>student.progress<50);
 const stats=[[new Set(students.map(student=>student.studentId)).size,"Total Students","users"],[`${average(students)}%`,"Average Progress","layers"],[students.filter(student=>student.progress===100).length,"Completed Enrollments","check"],[lower.length,"Below 50% Progress","clock"]];
 return <section className="tsp-page"><header><h1>Student Progress</h1><p>Track learning progress across your assigned courses and batches.</p></header><div className="tsp-stats">{stats.map(([value,label,icon])=><article key={label}><span><PublicIcon name={icon}/></span><div><strong>{value}</strong><p>{label}</p></div></article>)}</div><section><header className="tsp-section-heading"><div><h2>Class Performance</h2><p>Progress overview by course.</p></div><Link to="/teacher/courses">View All Courses</Link></header><div className="tsp-courses">{courses.map(course=>{const rows=students.filter(student=>student.courseId===course.id);return <article key={course.id}><h3>{course.title}</h3><p>{new Set(rows.map(row=>row.studentId)).size} Students</p><div className="tsp-progress-label"><span>Average Progress</span><strong>{average(rows)}%</strong></div><progress value={average(rows)} max="100" aria-label={`${course.title} average progress`}/><dl><div><dt>Completed</dt><dd>{rows.filter(row=>row.progress===100).length}</dd></div><div><dt>Below 50%</dt><dd>{rows.filter(row=>row.progress<50).length}</dd></div></dl><Link to="/teacher/students">View Students</Link></article>;})}{!courses.length && <p>No assigned courses yet.</p>}</div></section><div className="tsp-student-lists">{[["Highest Progress",[...students].sort((a,b)=>b.progress-a.progress)],["Lower Progress",[...lower].sort((a,b)=>a.progress-b.progress)]].map(([title,rows])=><section key={title}><header className="tsp-section-heading"><h2>{title}</h2><Link to="/teacher/students">View All</Link></header>{rows.slice(0,5).map(student=><article key={student.id}><span className="tsp-avatar">{student.name.charAt(0)}</span><div className="tsp-student-name"><strong>{student.name}</strong><small>{student.course} ? {student.batch}</small></div><div className="tsp-score"><strong>{student.progress}%</strong><progress value={student.progress} max="100" aria-label={`${student.name} progress`}/></div></article>)}{!rows.length && <p>No students in this group.</p>}</section>)}</div></section>;
}
