import { useState } from "react";
import { useSearchParams, Link } from "react-router-dom";
import useCourses from "../../utils/useCourses";
import useBatches from "../../utils/useBatches";
import { submitPayment, paymentRecords, receivingAccounts, studentId } from "../../utils/batchStorage";
import { readProfile } from "../../utils/profileStorage";
import { students } from "../../data/operations";
import ReceivingAccount from "../../components/ReceivingAccount";
import "./Payments.css";
export default function Payments(){
 const [params]=useSearchParams();const catalog=useCourses();const state=useBatches();const [form,setForm]=useState({courseId:params.get("course")||"",batchId:"",receivingAccountId:"",senderName:"",senderAccount:"",transactionId:"",amount:"",paymentDate:new Date().toISOString().slice(0,10),receipt:null});const [message,setMessage]=useState("");
 const course=catalog.find(item=>String(item.id)===form.courseId);const batches=state.batches.filter(batch=>batch.courseId===course?.id && ["Active","Upcoming"].includes(batch.status));
 const accounts=receivingAccounts(state, true);
 const requests=paymentRecords(state).filter(item=>item.studentId===studentId);
 return <section className="student-payments"><h1>Course Enrollment &amp; Payment</h1><ReceivingAccount title="Available Payment Accounts" selectable selectedId={form.receivingAccountId || (accounts.length===1 ? accounts[0].id : "")} onSelect={id=>setForm({...form,receivingAccountId:id})}/><p>Transfer payment to one of the active global accounts above, then submit your transaction details for review. This form does not transfer money.</p>{course && <p>Student: {readProfile(studentId,students.find(item=>item.id===studentId)).name} · Course: {course.title} · Instructor: {course.instructor} · Price: PKR {course.price}</p>}<form onSubmit={event=>{event.preventDefault();try{submitPayment(form,readProfile(studentId,students.find(item=>item.id===studentId)).name);setMessage("Payment submitted for verification. Course access will appear after approval.");}catch(error){setMessage(error.message);}}}><label>Course<select required value={form.courseId} onChange={event=>setForm({...form,courseId:event.target.value,batchId:""})}><option value="">Select course</option>{catalog.filter(item=>item.status==="Published" && item.availability!=="Unavailable").map(item=><option value={item.id} key={item.id}>{item.title} - PKR {item.price}</option>)}</select></label><label>Batch<select value={form.batchId} required={batches.length>0} onChange={event=>setForm({...form,batchId:event.target.value})}><option value="">{batches.length?"Select batch":"Awaiting Admin assignment"}</option>{batches.map(batch=><option value={batch.id} key={batch.id}>{batch.name} ({batch.status})</option>)}</select></label>{[["senderName","Sender Account Holder Name"],["senderAccount","Sender Account / Wallet Number"],["transactionId","Transaction ID"],["amount","Amount Paid (PKR)"],["paymentDate","Payment Date"]].map(([key,label])=><label key={key}>{label}<input required type={key==="amount"?"number":key==="paymentDate"?"date":"text"} min={key==="amount"?"0.01":undefined} step={key==="amount"?"0.01":undefined} value={form[key]} onChange={event=>setForm({...form,[key]:event.target.value})}/></label>)}<label>Receipt / Proof (optional)<input type="file" accept=".pdf,image/*" onChange={event=>{const file=event.target.files?.[0];setForm({...form,receipt:file ? {name:file.name,type:file.type,size:file.size} : null});}}/></label><button disabled={!accounts.length}>Submit Enrollment Request</button></form>{message&&<p role="status">{message}</p>}<h2>My Requests</h2>{requests.map(item=><article key={item.transactionId}><strong>{item.courseTitle || item.course}</strong><p>Payment: {item.status} · Enrollment: {item.enrollmentStatus || (item.status === "Approved" ? "Active" : "Pending")} · Batch: {item.batch || "Awaiting assignment"} · Submitted: {item.submittedAt || item.date}</p>{item.status==="Approved"&&<Link to="/student/courses">My Courses</Link>}</article>)}</section>;
}
