import "./Assignments.css";
import { useRef, useState } from "react";
import { assignments } from "../../data/operations";
import PublicIcon from "../../components/PublicIcon";

export default function Assignments() {
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("");
  const [selected, setSelected] = useState(null);
  const dialog = useRef(null);
  const submitted = assignments.reduce((sum, row) => sum + row.submissions, 0);
  const expected = assignments.reduce((sum, row) => sum + row.totalStudents, 0);
  const completed = assignments.filter(row => row.status === "Completed").length;
  const visible = assignments.filter(row => (!status || row.status === status) && [row.title, row.course, row.teacher, row.batch].some(value => value.toLowerCase().includes(search.trim().toLowerCase())));
  const stats = [["Total Assignments", assignments.length, "book"], ["Awaiting Submission", expected - submitted, "clock"], ["Total Submissions", submitted, "users"], ["Completed", completed, "check"]];
  function preview(row) { setSelected(row); dialog.current.showModal(); }
  return <section className="admin-assignments">
    <header className="aa-banner"><div><h1>Assignments</h1><p>Manage assignments, submissions, grading, and deadlines across all courses.</p></div><blockquote>“Assessment drives learning,<br/> not the other way around.”<cite>— Dylan Wiliam</cite></blockquote><PublicIcon name="book"/><PublicIcon name="cap"/></header>
    <div className="aa-stats">{stats.map(([label, value, icon], index) => <article key={label} className={`aa-tone-${index}`}><span className="aa-icon"><PublicIcon name={icon}/></span><div><strong>{value}</strong><span>{label}</span><small>Across all assignments</small></div></article>)}</div>
    <div className="aa-toolbar"><div className="aa-tabs">{[["", "All Assignments"], ["Active", "Active"], ["Completed", "Completed"]].map(([value, label]) => <button key={value} aria-pressed={status === value} onClick={() => setStatus(value)}>{label} ({value ? assignments.filter(row => row.status === value).length : assignments.length})</button>)}</div><label className="aa-search"><PublicIcon name="search"/><input type="search" aria-label="Search assignments" placeholder="Search assignments, courses, or teachers..." value={search} onChange={event => setSearch(event.target.value)}/></label></div>
    <div className="aa-columns"><div className="aa-main"><section className="aa-panel"><h2>Assignments</h2><div className="aa-table-scroll" tabIndex="0" aria-label="Assignment records"><table><thead><tr>{["Assignment Details", "Course & Batch", "Teacher", "Due Date", "Submissions", "Status", "Actions"].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{visible.map((row, index) => <tr key={row.title}><td><div className={`aa-title aa-tone-${index % 4}`}><span className="aa-icon"><PublicIcon name="book"/></span><strong>{row.title}<small>Course assignment</small></strong></div></td><td><strong>{row.course}</strong><small>{row.batch}</small></td><td><div className="aa-teacher"><span className="aa-avatar">{row.teacher.split(" ").map(part => part[0]).join("")}</span>{row.teacher}</div></td><td>{row.dueDate}</td><td><strong>{row.submissions} / {row.totalStudents}</strong><progress value={row.submissions} max={row.totalStudents}/><small>{Math.round(row.submissions / row.totalStudents * 100)}%</small></td><td><span className={`aa-badge ${row.status === "Completed" ? "aa-complete" : ""}`}>{row.status}</span></td><td><button onClick={() => preview(row)}>View</button></td></tr>)}{!visible.length && <tr><td colSpan="7">No matching assignments.</td></tr>}</tbody></table></div><p className="aa-count" role="status">Showing {visible.length} of {assignments.length} assignments</p></section>
    <div className="aa-bottom"><section className="aa-panel"><h2>Submission Summary</h2>{assignments.map(row => <button className="aa-summary-row" key={row.title} onClick={() => preview(row)}><span><strong>{row.title}</strong><small>{row.course} · {row.batch}</small></span><span>{row.submissions} submitted <PublicIcon name="arrow"/></span></button>)}</section><section className="aa-panel"><h2>Submission Overview</h2><div className="aa-overview"><div className="aa-ring" style={{"--submitted": `${submitted / expected * 100}%`}}><div><strong>{submitted}</strong><small>Total Submissions</small></div></div><p><span className="aa-dot"/> Submitted <strong>{submitted}</strong></p><p><span className="aa-dot aa-waiting"/> Awaiting submission <strong>{expected - submitted}</strong></p></div></section></div></div>
    <aside><section className="aa-panel"><h2>Active Assignments</h2>{assignments.filter(row => row.status === "Active").map((row, index) => <div className={`aa-queue aa-tone-${index}`} key={row.title}><span className="aa-icon"><PublicIcon name="book"/></span><div><strong>{row.title}</strong><small>{row.course}<br/>{row.batch}</small></div><button onClick={() => preview(row)}>View</button></div>)}</section><section className="aa-panel aa-quick"><h2>Quick Filters</h2><div>{[["", "All Assignments", "book"], ["Active", "Active Assignments", "clock"], ["Completed", "Completed", "check"]].map(([value, label, icon]) => <button key={value} onClick={() => { setStatus(value); setSearch(""); }}><PublicIcon name={icon}/>{label}</button>)}</div></section></aside></div>
    <dialog ref={dialog} aria-labelledby="aa-details"><h2 id="aa-details">Assignment Details</h2>{selected && <dl>{Object.entries({Assignment: selected.title, Course: selected.course, Batch: selected.batch, Teacher: selected.teacher, "Due Date": selected.dueDate, Submissions: `${selected.submissions} / ${selected.totalStudents}`, Status: selected.status}).map(([label,value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>}<form method="dialog"><button>Close</button></form></dialog>
  </section>;
}
