import ReceivingAccount from "../../components/ReceivingAccount";
import "./Payments.css";
import { useRef, useState } from "react";
import useBatches from "../../utils/useBatches";
import { paymentRecords, approvePayment, rejectPayment } from "../../utils/batchStorage";
import PublicIcon from "../../components/PublicIcon";

export default function Payments() {
  const payments = paymentRecords(useBatches());
  const [message,setMessage] = useState("");
  const [tab, setTab] = useState("all");
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("");
  const [course, setCourse] = useState("");
  const [batch, setBatch] = useState("");
  const [selected, setSelected] = useState(null);
  const dialog = useRef(null);
  const visible = payments.filter(row => (tab !== "history" || row.status !== "Pending") && (!status || row.status === status) && (!course || row.course === course) && (!batch || row.batch === batch) && [row.student, row.studentId, row.transactionId].some(value => value.toLowerCase().includes(search.trim().toLowerCase())));
  const stats = [["Pending Verification", payments.filter(row => row.status === "Pending").length, "clock"], ["Approved Payments", payments.filter(row => row.status === "Approved").length, "check"], ["Rejected Payments", payments.filter(row => row.status === "Rejected").length, "close"], ["Total Amount", "PKR " + payments.reduce((sum,row) => sum + Number(row.amount.replace(/[^0-9.]/g,"")),0).toLocaleString(), "database"]];
  return <section className="admin-payments"><header className="ap-banner"><div><h1>Payments &amp; Verification</h1><p>Review and verify student payments for course enrollments.</p></div><blockquote>&ldquo;A reliable payment system builds<br/>trust and empowers education for all.&rdquo;<cite>&mdash; Learnova</cite></blockquote><PublicIcon name="briefcase"/><PublicIcon name="check"/></header><div className="ap-stats">{stats.map(([label,value,icon],index) => <article className={`ap-tone-${index}`} key={label}><span className="ap-icon"><PublicIcon name={icon}/></span><div><strong>{value}</strong><p>{label}</p><small>{index === 0 ? "Needs your review" : "Existing payment records"}</small></div></article>)}</div>
    <ReceivingAccount editable/><section className="ap-panel"><div className="ap-tabs">{[["all","Payment Requests"],["history","Verification History"]].map(([value,label]) => <button key={value} aria-pressed={tab === value} onClick={() => setTab(value)}>{label}</button>)}</div><div className="ap-filters"><select aria-label="Payment status" value={status} onChange={event => setStatus(event.target.value)}><option value="">All Statuses</option>{[...new Set(payments.map(row => row.status))].map(value => <option key={value}>{value}</option>)}</select><select aria-label="Filter course" value={course} onChange={event => setCourse(event.target.value)}><option value="">All Courses</option>{[...new Set(payments.map(row => row.course))].map(value => <option key={value}>{value}</option>)}</select><select aria-label="Filter batch" value={batch} onChange={event => setBatch(event.target.value)}><option value="">All Batches</option>{[...new Set(payments.map(row => row.batch))].map(value => <option key={value}>{value}</option>)}</select><label className="ap-search"><PublicIcon name="search"/><input type="search" aria-label="Search payments" placeholder="Search student name, transaction ID..." value={search} onChange={event => setSearch(event.target.value)}/></label></div>
    <div className="ap-table" tabIndex="0" aria-label="Payment records"><table><thead><tr>{["#","Student","Course","Batch","Payment Method","Transaction ID","Date","Amount","Status","Action"].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{visible.map((row,index) => <tr key={row.transactionId}><td>{index + 1}</td><td><div className="ap-student"><span>{row.student.split(" ").map(part => part[0]).join("")}</span><div><strong>{row.student}</strong><small>{row.studentId}</small></div></div></td><td>{row.course}</td><td>{row.batch}</td><td><span className="ap-method"><PublicIcon name="briefcase"/>{row.method}</span></td><td>{row.transactionId}</td><td>{row.date}</td><td><strong>{row.amount}</strong></td><td><span className={`ap-badge ap-${row.status.toLowerCase()}`}>{row.status}</span></td><td><button className={row.status === "Pending" ? "ap-review" : ""} onClick={() => { setSelected(row); dialog.current.showModal(); }}>{row.status === "Pending" ? "Review" : "View"}</button></td></tr>)}{!visible.length && <tr><td colSpan="10">No matching payments.</td></tr>}</tbody></table></div><footer role="status">Showing {visible.length} of {payments.length} payments</footer></section>
    <dialog ref={dialog} aria-labelledby="ap-details"><h2 id="ap-details">Payment Details</h2>{selected && <dl>{[["student","Student"],["studentId","Student ID"],["course","Course"],["batch","Batch"],["method","Payment Method"],["senderName","Sender Name"],["senderAccount","Sender Account"],["receiver","Receiving Account"],["transactionId","Transaction ID"],["date","Date"],["amount","Amount"],["status","Status"]].map(([key,label]) => <div key={key}><dt>{label}</dt><dd>{selected[key]}</dd></div>)}</dl>}{selected?.status === "Pending" && <button onClick={() => {try{approvePayment(selected.transactionId,"admin");setSelected({...selected,status:"Approved"});setMessage("Payment approved and course assigned.");}catch(error){setMessage(error.message);}}}>Approve Payment</button>}{selected?.status === "Pending" && <button onClick={()=>{try{rejectPayment(selected.transactionId,"admin");setSelected({...selected,status:"Rejected"});setMessage("Request rejected; no course access granted.");}catch(error){setMessage(error.message);}}}>Reject Request</button>}{message && <p role="status">{message}</p>}<form method="dialog"><button>Close</button></form></dialog>
  </section>;
}
