import { test } from "node:test";
import assert from "node:assert/strict";

const storage = () => {
  const entries = new Map();
  return { getItem: key => entries.get(key) ?? null, setItem: (key, value) => entries.set(key, value), removeItem: key => entries.delete(key) };
};
globalThis.localStorage = storage();
globalThis.sessionStorage = storage();
globalThis.window = new EventTarget();
const accounts = await import("./adminPermissions.js");

test("renaming an ID preserves credentials, profile, permissions and session", async () => {
  const input = { id: "SA-RENAME", name: "Rename Test", email: "rename@example.com", password: "Rename-test-123", status: "Active" };
  await accounts.createSubAdmin(input);
  accounts.changeAdminPermission(input.id, "courses", true);
  const profile = JSON.stringify({ name: input.name, phone: "12345" });
  localStorage.setItem(`learnova_profile_${input.id}`, profile);
  await accounts.loginSubAdmin(input.id, input.password);
  await assert.rejects(accounts.updateSubAdmin(input.id, { ...input, id: "sa-1002" }), /already exists/);
  await assert.rejects(accounts.updateSubAdmin(input.id, { ...input, id: "bad id" }), /ID must/);
  const newId = "SA-RENAMED";
  await accounts.updateSubAdmin(input.id, { ...input, id: newId, password: "" });
  assert.equal(accounts.currentSubAdminId, newId);
  assert.equal(sessionStorage.getItem("learnova_subadmin_session"), newId);
  assert.equal(accounts.readAdminPermissions()[newId].courses, true);
  assert.equal(accounts.readAdminPermissions()[input.id], undefined);
  assert.equal(localStorage.getItem(`learnova_profile_${newId}`), profile);
  assert.equal(localStorage.getItem(`learnova_profile_${input.id}`), null);
  await assert.rejects(accounts.loginSubAdmin(input.id, input.password), /Invalid/);
  await accounts.loginSubAdmin(newId, input.password);
  const reloaded = await import("./adminPermissions.js?renamed");
  assert.ok(reloaded.subAdmins.some(person => person.id === newId));
  assert.ok(!reloaded.subAdmins.some(person => person.id === input.id));
  assert.equal(reloaded.readAdminPermissions()[newId].courses, true);
  accounts.deleteSubAdmin(newId);
});

test("create, persist, validate credentials, apply assigned permissions and logout", async () => {
  assert.ok(Object.values(accounts.readAdminPermissions()["SA-1001"]).every(value => value === false));
  accounts.changeAdminPermission("SA-1001", "liveClasses", true);
  assert.equal(accounts.canAccessSubAdminRoute("/admin/live-classes/class-123", accounts.readAdminPermissions(), "SA-1001"), true);
  accounts.changeAdminPermission("SA-1001", "liveClasses", false);
  assert.equal(accounts.canAccessSubAdminRoute("/admin/live-classes/class-123", accounts.readAdminPermissions(), "SA-1001"), false);
  const input = { name: "Test Operator", email: "test@example.com", id: "SA-2001", password: "Test-password-123", modules: { students: true } };
  const person = await accounts.createSubAdmin(input);
  assert.equal(person.id, input.id);
  assert.equal(person.password, undefined);
  assert.equal(person.demoPassword, input.password);
  assert.notEqual(person.passwordHash, input.password);
  assert.equal(accounts.readAdminPermissions()[person.id].students, true);
  assert.equal(accounts.readAdminPermissions()[person.id].courses, false);
  await assert.rejects(accounts.createSubAdmin({ ...input, id: "sa-2001", email: "other@example.com" }), /already exists/);
  await assert.rejects(accounts.createSubAdmin({ ...input, id: "SA-2002" }), /already exists/);
  await assert.rejects(accounts.createSubAdmin({ ...input, password: "short" }), /8 characters/);
  await assert.rejects(accounts.loginSubAdmin(person.id, "incorrect"), /Invalid/);
  assert.equal(accounts.currentSubAdminId, "");
  await accounts.loginSubAdmin("TEST@example.com", input.password);
  assert.equal(accounts.currentSubAdminId, person.id);
  assert.equal(accounts.canAccessSubAdminRoute("/admin/students", accounts.readAdminPermissions()), true);
  assert.equal(accounts.canAccessSubAdminRoute("/admin/courses", accounts.readAdminPermissions()), false);
  accounts.changeAdminPermission(person.id, "courses", true);
  assert.equal(accounts.readAdminPermissions()[person.id].courses, true);
  const reloaded = await import("./adminPermissions.js?reload");
  assert.ok(reloaded.subAdmins.some(row => row.id === person.id && row.lastLogin));
  assert.equal(reloaded.currentSubAdminId, person.id);
  accounts.logoutSubAdmin();
  localStorage.setItem(accounts.ADMIN_PERMISSION_KEY, JSON.stringify({ [person.id]: {} }));
  assert.ok(Object.values(accounts.readAdminPermissions()[person.id]).every(value => value === false));
  assert.equal(accounts.currentSubAdminId, "");
  assert.equal(sessionStorage.getItem("learnova_subadmin_session"), null);
  await accounts.loginSubAdmin(person.id, input.password);
  assert.equal(accounts.currentSubAdminId, person.id);
  accounts.logoutSubAdmin();
});

test("edit and delete persist for created and original accounts", async () => {
  const id = "SA-2001";
  await accounts.updateSubAdmin(id, { name: "Updated Operator", email: "updated@example.com", status: "Active", password: "Replacement-123" });
  assert.equal(accounts.subAdmins.find(person => person.id === id).demoPassword, "Replacement-123");
  const passwordReload = await import("./adminPermissions.js?password-replaced");
  assert.equal(passwordReload.subAdmins.find(person => person.id === id).demoPassword, "Replacement-123");
  await assert.rejects(accounts.loginSubAdmin(id, "Test-password-123"), /Invalid/);
  await accounts.loginSubAdmin("updated@example.com", "Replacement-123");
  await assert.rejects(accounts.updateSubAdmin(id, { name: "Duplicate", email: "subadmin@learnova.com", status: "Active" }), /already exists/);
  await accounts.updateSubAdmin(id, { name: "Updated Operator", email: "updated@example.com", status: "Inactive" });
  assert.equal(accounts.subAdmins.find(person => person.id === id).demoPassword, "Replacement-123");
  await assert.rejects(accounts.loginSubAdmin(id, "Replacement-123"), /Invalid/);
  assert.equal(accounts.hasPermission("subadmin", id, "students"), false);
  await accounts.updateSubAdmin(id, { name: "Updated Operator", email: "updated@example.com", status: "Active" });
  await accounts.loginSubAdmin(id, "Replacement-123");
  accounts.changeAdminPermission(id, "students", true);
  accounts.deleteSubAdmin(id);
  assert.equal(accounts.currentSubAdminId, "");
  assert.equal(accounts.readAdminPermissions()[id], undefined);
  await assert.rejects(accounts.loginSubAdmin(id, "Replacement-123"), /Invalid/);
  await accounts.updateSubAdmin("SA-1001", { name: "Original Updated", email: "original@example.com", status: "Active", password: "Original-123" });
  await accounts.loginSubAdmin("SA-1001", "Original-123");
  assert.equal(accounts.subAdmins.find(person => person.id === "SA-1001").demoPassword, "Original-123");
  const edited = await import("./adminPermissions.js?edited");
  assert.equal(edited.subAdmins.find(person => person.id === "SA-1001").name, "Original Updated");
  accounts.deleteSubAdmin("SA-1001");
  const reloaded = await import("./adminPermissions.js?deleted");
  assert.ok(!reloaded.subAdmins.some(person => [id, "SA-1001"].includes(person.id)));
  assert.ok(reloaded.subAdmins.some(person => person.id === "SA-1002"));
  await assert.rejects(accounts.updateSubAdmin(id, { name: "Missing", email: "missing@example.com", status: "Active" }), /no longer exists/);
});
