import { useRef, useState } from "react";
import useBatches from "../../utils/useBatches";
import useCourses from "../../utils/useCourses";
import { usePeople } from "../../utils/peopleStorage";
import { createManagedBatch, updateManagedBatch, deleteManagedBatch } from "../../utils/batchStorage";
import { AdminHeading } from "../../components/AdminSummary";
import PublicIcon from "../../components/PublicIcon";
import "./Batches.css";
import BatchStudents from "./BatchStudents";
import { batchStudents } from "../../utils/studentDirectory";
const emptyForm={name:"",courseId:"",teacherId:"",startDate:"",endDate:"",mode:"Online"};
function isBackdropClick(event) {
 const dialog = event.currentTarget;
 const bounds = dialog.getBoundingClientRect();
 return event.target === dialog && (event.clientX < bounds.left || event.clientX > bounds.right || event.clientY < bounds.top || event.clientY > bounds.bottom);
}
export default function Batches() {
 const backdropStart = useRef(null);
 function startBackdropClick(event) { backdropStart.current = isBackdropClick(event) ? event.currentTarget : null; }
 function closeOnBackdrop(event) {
  if (backdropStart.current === event.currentTarget && isBackdropClick(event)) event.currentTarget.close();
  backdropStart.current = null;
 }
 usePeople("students");
 const state=useBatches(), courses=useCourses(), teachers=usePeople(), batches=state.batches;
 const [search,setSearch]=useState(""),[filters,setFilters]=useState({}),[page,setPage]=useState(1),[size,setSize]=useState(10),[selected,setSelected]=useState([]);
 const [detail,setDetail]=useState(null),[form,setForm]=useState(emptyForm),[message,setMessage]=useState("");
 const [editingId,setEditingId]=useState(null),[formError,setFormError]=useState(""),[appliedFilters,setAppliedFilters]=useState({}),[menuId,setMenuId]=useState(null);
 const createDialog=useRef(null),detailDialog=useRef(null);
 const [studentBatch,setStudentBatch]=useState(null);
 function openForm(row) { setEditingId(row?.id||null);setForm(row?{name:row.name,courseId:row.courseId,teacherId:row.teacherId,startDate:row.startDate||"",endDate:row.endDate||"",mode:row.mode||"Online"}:{...emptyForm});setFormError("");setMenuId(null);createDialog.current.showModal(); }
 function remove(row) {setMenuId(null);if(!window.confirm(`Delete ${row.name}? This cannot be undone.`))return;try{deleteManagedBatch(row.id,"subadmin");setSelected(ids=>ids.filter(id=>id!==row.id));setMessage("Batch deleted.");}catch(error){setMessage(error.message);}}
 const displayDate=value=>{if(!value)return "Not recorded";const date=new Date(`${value}T00:00:00`);return Number.isNaN(date.getTime())?value:date.toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"});};
 const visible=batches.filter(row=>`${row.name} ${row.course} ${row.teacher}`.toLowerCase().includes(search.toLowerCase())&&Object.entries(appliedFilters).every(([key,value])=>!value||row[key]===value));
 const pages=Math.max(1,Math.ceil(visible.length/size)),current=Math.min(page,pages),start=(current-1)*size,displayed=visible.slice(start,start+size);
 function save(event){event.preventDefault();try{if(editingId)updateManagedBatch(editingId,form,"subadmin");else createManagedBatch(form,"subadmin");setForm(emptyForm);createDialog.current.close();setMessage(editingId?"Batch updated.":"Batch created.");}catch(error){setFormError(error.message);}}
 function exportRows(){const keys=["name","course","teacher","startDate","endDate","students","mode","status"];const rows=selected.length?visible.filter(row=>selected.includes(row.id)):visible;const quote=value=>{const text=String(value??"");return '"'+(/^[=+@\-\t\r]/.test(text)?"'"+text:text).replace(/"/g,'""')+'"';};const csv=[keys,...rows.map(row=>keys.map(key=>key==="students"?batchStudents(row,state.enrollments).length:row[key]))].map(row=>row.map(quote).join(",")).join("\r\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download="batches.csv";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="sa-page sab-page"><AdminHeading title="Batches" subtitle="Manage active and upcoming course batches." icon="users"><button className="sab-primary" onClick={()=>openForm(null)}>+ Create Batch</button></AdminHeading>
 <div className="sab-stats">{[["Total Batches",batches.length,"users","purple"],["Active Batches",batches.filter(b=>b.status==="Active").length,"check","green"],["Upcoming Batches",batches.filter(b=>b.status==="Upcoming").length,"clock","orange"],["Completed Batches",batches.filter(b=>b.status==="Completed").length,"cap","blue"]].map(([label,value,icon,tone])=><article key={label}><span className={`sab-stat-icon sab-${tone}`}><PublicIcon name={icon}/></span><div><strong>{value}</strong><p>{label}</p><small>{label==="Total Batches"?"All course batches":`${batches.length?Math.round(value/batches.length*100):0}% of total batches`}</small></div></article>)}</div>
 <section className="sab-panel"><div className="sab-tools"><label className="sab-search"><PublicIcon name="search"/><input type="search" aria-label="Search batches" placeholder="Search batches..." value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></label>{[["course","Courses"],["teacher","Instructors"],["mode","Modes"],["status","Statuses"]].map(([key,label])=><select key={key} aria-label={`Filter ${label}`} value={filters[key]||""} onChange={e=>{setFilters({...filters,[key]:e.target.value});setPage(1);}}><option value="">All {label}</option>{[...new Set(key==="mode"?["Online","Live Class","In Person","Hybrid"]:batches.map(row=>row[key]).filter(Boolean))].map(value=><option key={value}>{value}</option>)}</select>)}<button className="sab-filter-button" onClick={()=>{setAppliedFilters({...filters});setPage(1);}}><svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M3 4h18l-7 8v8l-4-2v-6Z"/></svg>Filter</button><button className="sab-export" onClick={exportRows}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path d="M12 3v12m-4-4 4 4 4-4M4 15v5h16v-5"/></svg>Export</button></div>
 {Object.values(appliedFilters).some(Boolean)&&<div className="sab-applied">Filters applied<button onClick={()=>{setFilters({});setAppliedFilters({});setPage(1);}}>Clear filters</button></div>}
 {message&&<p role="status" className="sab-message">{message}</p>}
 <div className="sab-table-wrap"><table><thead><tr><th><input type="checkbox" aria-label="Select displayed batches" checked={displayed.length>0&&displayed.every(row=>selected.includes(row.id))} onChange={e=>setSelected(e.target.checked?[...new Set([...selected,...displayed.map(row=>row.id)])]:selected.filter(id=>!displayed.some(row=>row.id===id)))}/></th>{["#","Batch Name","Course","Instructor","Start Date","End Date","Students","Mode","Status","Action"].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{displayed.map((row,index)=>{const teacher=teachers.find(t=>t.id===row.teacherId);return <tr key={row.id}><td><input type="checkbox" aria-label={`Select ${row.name}`} checked={selected.includes(row.id)} onChange={e=>setSelected(e.target.checked?[...selected,row.id]:selected.filter(id=>id!==row.id))}/></td><td>{start+index+1}</td><td><strong>{row.name}</strong></td><td>{row.course}</td><td><div className="sab-person"><span>{teacher?.image?<img src={teacher.image} alt=""/>:(teacher?.name||row.teacher||"?").split(" ").map(part=>part[0]).slice(0,2).join("")}</span>{teacher?.name||row.teacher||"Unassigned"}</div></td><td>{displayDate(row.startDate)}</td><td>{displayDate(row.endDate)}</td><td>{batchStudents(row,state.enrollments).length}</td><td>{row.mode||"Not specified"}</td><td><span className="sa-status" data-status={row.status}>{row.status}</span></td><td><div className="sab-row-actions"><button className="sab-view" aria-label={`View ${row.name}`} onClick={()=>{setDetail(row);detailDialog.current.showModal();}}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></svg></button><button className="sab-view sab-edit" aria-label={`Edit ${row.name}`} onClick={()=>openForm(row)}><PublicIcon name="design"/></button><button className="sab-view" aria-label={`More actions for ${row.name}`} aria-expanded={menuId===row.id} onClick={()=>setMenuId(menuId===row.id?null:row.id)}>&#8942;</button>{menuId===row.id&&<div className="sab-row-menu"><button onClick={()=>{setStudentBatch(row);setMenuId(null);}}>View students</button><button className="sab-delete" onClick={()=>remove(row)}>Delete batch</button></div>}</div></td></tr>;})}{!displayed.length&&<tr><td colSpan={11}>No matching batches.</td></tr>}</tbody></table></div>
 <footer className="sab-pagination"><span>Showing {visible.length?start+1:0} to {Math.min(start+size,visible.length)} of {visible.length} batches</span><select aria-label="Batches per page" value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1);}}>{[10,20,50].map(value=><option key={value} value={value}>{value} per page</option>)}</select><nav aria-label="Batch pages"><button disabled={current===1} aria-label="Previous page" onClick={()=>setPage(current-1)}>&lsaquo;</button>{Array.from({length:pages},(_,i)=>i+1).filter(n=>n===1||n===pages||Math.abs(n-current)<=1).map(n=><button key={n} aria-current={n===current?"page":undefined} onClick={()=>setPage(n)}>{n}</button>)}<button disabled={current===pages} aria-label="Next page" onClick={()=>setPage(current+1)}>&rsaquo;</button></nav></footer></section>
 <dialog onPointerDown={startBackdropClick} onClick={closeOnBackdrop} ref={createDialog} aria-labelledby="sab-create-title"><h2 id="sab-create-title">{editingId?"Edit Batch":"Create Batch"}</h2><form onSubmit={save}><div className="sab-form"><label>Batch Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Course<select required value={form.courseId} onChange={e=>setForm({...form,courseId:e.target.value})}><option value="">Select course</option>{courses.map(row=><option key={row.id} value={row.id}>{row.title}</option>)}</select></label><label>Instructor<select required value={form.teacherId} onChange={e=>setForm({...form,teacherId:e.target.value})}><option value="">Select instructor</option>{teachers.filter(t=>t.status==="Active"||t.id===form.teacherId).map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label>Mode<select value={form.mode} onChange={e=>setForm({...form,mode:e.target.value})}>{["Online","Live Class","In Person","Hybrid"].map(value=><option key={value}>{value}</option>)}</select></label>{[["startDate","Start Date"],["endDate","End Date"]].map(([key,label])=><label key={key}>{label}<input type="date" value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</div>{formError&&<p role="alert" className="sab-error">{formError}</p>}<footer><button type="button" onClick={()=>createDialog.current.close()}>Cancel</button><button className="sab-primary">{editingId?"Save Changes":"Create Batch"}</button></footer></form></dialog>
 <dialog onPointerDown={startBackdropClick} onClick={closeOnBackdrop} ref={detailDialog} aria-labelledby="sab-detail-title"><h2 id="sab-detail-title">{detail?.name}</h2>{detail&&<><dl>{[["course","Course"],["teacher","Instructor"],["startDate","Start Date"],["endDate","End Date"],["students","Students"],["mode","Mode"],["status","Status"]].map(([key,label])=><div key={key}><dt>{label}</dt><dd>{key==="students"?batchStudents(detail,state.enrollments).length:detail[key]??"Not recorded"}</dd></div>)}</dl><h3>Students</h3><p>{batchStudents(detail,state.enrollments).length} student records assigned</p><button onClick={()=>{detailDialog.current.close();setStudentBatch(detail);}}>View students</button></>}<button onClick={()=>detailDialog.current.close()}>Close</button></dialog>
 <BatchStudents batch={studentBatch} state={state} onClose={()=>setStudentBatch(null)}/>
 </section>;
}
