import "./LecturesContent.css";
import { useRef, useState } from "react";
import { content } from "../../data/operations";
import PublicIcon from "../../components/PublicIcon";

export default function LecturesContent() {
  const [search, setSearch] = useState("");
  const [course, setCourse] = useState("");
  const [status, setStatus] = useState("");
  const [selected, setSelected] = useState(null);
  const dialog = useRef(null);
  const visible = content.filter(row => (!course || row.course === course) && (!status || row.status === status) && [row.title, row.course, row.teacher, row.module || ""].some(value => value.toLowerCase().includes(search.trim().toLowerCase())));
  const stats = [["Total Lectures", content.length, "video"], ["Published Content", content.filter(row => row.status === "Published").length, "book"], ["Draft Content", content.filter(row => row.status === "Draft").length, "design"], ["Learning Materials", content.reduce((sum, row) => sum + (row.materials || 0), 0), "briefcase"]];
  function view(row) { setSelected(row); dialog.current.showModal(); }
  return <section className="admin-content-page">
    <header className="alc-banner"><div><h1>Lectures &amp; Content</h1><p>Manage lectures, modules, notes, videos, and learning materials across all courses.</p></div><blockquote>&ldquo;Knowledge grows when<br/>it is shared.&rdquo;<cite>&mdash; Learnova</cite></blockquote><PublicIcon name="book"/><PublicIcon name="video"/></header>
    <div className="alc-stats">{stats.map(([label,value,icon],index) => <article className={`alc-tone-${index}`} key={label}><span className="alc-icon"><PublicIcon name={icon}/></span><div><strong>{value}</strong><p>{label}</p><small>Shared teaching content</small></div></article>)}</div>
    <div className="alc-tools"><div className="alc-tabs">{[["", "All Content"], ["Published", "Published"], ["Draft", "Drafts"]].map(([value,label]) => <button key={value} aria-pressed={status === value} onClick={() => setStatus(value)}>{label} ({value ? content.filter(row => row.status === value).length : content.length})</button>)}</div><select aria-label="Filter course" value={course} onChange={event => setCourse(event.target.value)}><option value="">All Courses</option>{[...new Set(content.map(row => row.course))].map(value => <option key={value}>{value}</option>)}</select><label className="alc-search"><PublicIcon name="search"/><input type="search" aria-label="Search content" placeholder="Search lectures, modules..." value={search} onChange={event => setSearch(event.target.value)}/></label></div>
    <section className="alc-panel"><div className="alc-table" tabIndex="0" aria-label="Content records"><table><thead><tr>{["Content Details", "Course", "Batch", "Module", "Instructor", "Status", "Materials", "Actions"].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{visible.map((row,index) => <tr key={`${row.course}-${row.batch}-${row.title}`}><td><div className={`alc-title alc-tone-${index % 4}`}><span className="alc-icon"><PublicIcon name="video"/></span><div><strong>{row.title}</strong><small>{row.type}{row.duration && ` · ${row.duration}`}</small></div></div></td><td>{row.course}</td><td>{row.batch}</td><td>{row.module || row.lecture || "Not specified"}</td><td><div className="alc-teacher"><span>{row.teacher.split(" ").map(part => part[0]).join("")}</span>{row.teacher}</div></td><td><span className={`alc-badge ${row.status === "Published" ? "alc-published" : ""}`}>{row.status}</span></td><td>{row.materials ?? "Not specified"}</td><td><button onClick={() => view(row)}>View</button></td></tr>)}{!visible.length && <tr><td colSpan="8">No matching content.</td></tr>}</tbody></table></div><p className="alc-count" role="status">Showing {visible.length} of {content.length} items</p></section>
    <div className="alc-bottom"><section className="alc-panel"><h2>Learning Materials</h2>{content.filter(row => row.materials).map(row => <button className="alc-resource" key={`${row.batch}-${row.title}`} onClick={() => view(row)}><PublicIcon name="book"/><span><strong>{row.title}</strong><small>{row.course} · {row.batch}</small></span><span>{row.materials} materials</span><PublicIcon name="arrow"/></button>)}</section><section className="alc-panel"><h2>Content by Course</h2>{[...new Set(content.map(row => row.course))].map(name => <button className="alc-resource" key={name} onClick={() => { setCourse(name); setStatus(""); setSearch(""); }}><PublicIcon name="cap"/><span><strong>{name}</strong><small>{content.filter(row => row.course === name && row.status === "Published").length} published lectures</small></span><span>{content.filter(row => row.course === name).length} items</span><PublicIcon name="arrow"/></button>)}</section></div>
    <dialog ref={dialog} aria-labelledby="alc-details"><h2 id="alc-details">Content Details</h2>{selected && <dl>{[["title","Title"],["course","Course"],["batch","Batch"],["teacher","Instructor"],["type","Type"],["module","Module"],["duration","Duration"],["materials","Materials"],["status","Status"]].map(([key,label]) => <div key={key}><dt>{label}</dt><dd>{selected[key] ?? "Not specified"}</dd></div>)}</dl>}<form method="dialog"><button>Close</button></form></dialog>
  </section>;
}
