import "./SubAdmins.css";
import { useRef, useState } from "react";
import { Link } from "react-router-dom";
import { subAdmins, operationalPermissions, changeAdminPermission } from "../../utils/adminPermissions";
import usePermissions from "../../utils/usePermissions";
import PublicIcon from "../../components/PublicIcon";

export default function SubAdmins() {
  const permissions = usePermissions();
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("");
  const [module, setModule] = useState("");
  const [editing, setEditing] = useState(null);
  const [tab, setTab] = useState("Permissions");
  const [message, setMessage] = useState("");
  const dialog = useRef(null);
  const rows = subAdmins.filter(person => `${person.name} ${person.email} ${person.id}`.toLowerCase().includes(search.toLowerCase()) && (!status || person.status === status) && (!module || permissions[person.id]?.[module]));
  function open(person) { const initial = { ...permissions[person.id] }; setEditing({ person, initial, draft: { ...initial } }); setTab("Permissions"); setMessage(""); dialog.current.showModal(); }
  function toggle(id,key,value) { try { changeAdminPermission(id,key,value); setMessage("Permissions saved."); } catch(error) { setMessage(error.message); } }
  function save() {
    try { for (const [key] of operationalPermissions) if (editing.draft[key] !== editing.initial[key]) changeAdminPermission(editing.person.id,key,editing.draft[key]); dialog.current.close(); setMessage("Permissions saved."); }
    catch(error) { setMessage(error.message); }
  }
  const stats = [["Total Sub Admins",subAdmins.length,"users",0],["Active",subAdmins.filter(person=>person.status === "Active").length,"check",1],["Inactive",subAdmins.filter(person=>person.status === "Inactive").length,"users",2],["Pending Invitations",subAdmins.filter(person=>person.status === "Pending").length,"briefcase",4]];
  return <div className={`admin-subadmins${editing ? " asa-editing" : ""}`}>
    <header className="as-banner"><div><h1>Sub Admins</h1><p>Manage sub administrators, assign permissions and control access across your platform.</p></div><div className="as-banner-art"><span>“Great teams build great learning<br />experiences.”<small>— Learnova</small></span><PublicIcon name="users" /></div></header>
    <div className="as-stats">{stats.map(([label,value,icon,tone])=><article key={label} className={`as-tone-${tone}`}><span className="as-stat-icon"><PublicIcon name={icon}/></span><div><strong>{value}</strong><span>{label}</span><small>Account overview</small></div></article>)}</div>
    <section className="asa-panel"><div className="as-tools"><label className="as-search"><PublicIcon name="search"/><input aria-label="Search sub admins" placeholder="Search by name, email or ID..." value={search} onChange={event=>setSearch(event.target.value)}/></label><select aria-label="Access status" value={status} onChange={event=>setStatus(event.target.value)}><option value="">All Access Status</option>{[...new Set(subAdmins.map(person=>person.status))].map(value=><option key={value}>{value}</option>)}</select><select aria-label="Module" value={module} onChange={event=>setModule(event.target.value)}><option value="">All Modules</option>{operationalPermissions.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div>
      {message && !editing && <p role="status">{message}</p>}
      <div className="as-table-wrap"><table><thead><tr>{["Sub Admin","Sub Admin ID","Assigned Modules","Public Website Access","Status","Last Login","Actions"].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{rows.map(person=><tr key={person.id}><td><div className="as-student"><span className="as-avatar">{person.name.split(" ").map(part=>part[0]).slice(0,2).join("")}</span><div><strong>{person.name}</strong><small>{person.email}</small></div></div></td><td>{person.id}</td><td><div className="asa-tags">{operationalPermissions.filter(([key])=>permissions[person.id]?.[key]).map(([key,label])=><span key={key}>{label.replace(/^(Manage|View|Verify) /,"")}</span>)}{!operationalPermissions.some(([key])=>permissions[person.id]?.[key])&&<small>None assigned</small>}</div></td><td><input className="asa-switch" type="checkbox" role="switch" aria-label={`Public website access for ${person.name}`} checked={permissions[person.id]?.publicWebsite===true} onChange={event=>toggle(person.id,"publicWebsite",event.target.checked)}/></td><td><span className={`as-badge ${person.status==="Active"?"as-good":"as-inactive"}`}>● {person.status}</span></td><td>{person.lastLogin||"Not recorded"}</td><td><button className="as-view" aria-label={`Edit permissions for ${person.name}`} onClick={()=>open(person)}>⋯</button></td></tr>)}{!rows.length&&<tr><td colSpan="7" className="as-empty">No matching Sub Admins.</td></tr>}</tbody></table></div>
      <footer className="as-pagination"><span>Showing {rows.length} of {subAdmins.length} sub admins</span><nav aria-label="Sub Admin pages"><button disabled aria-label="Previous page">‹</button><button aria-current="page">1</button><button disabled aria-label="Next page">›</button></nav></footer>
    </section>
    <dialog ref={dialog} className="asa-drawer" onClose={()=>setEditing(null)} aria-labelledby="asa-drawer-title">{editing&&<><div className="asa-drawer-heading"><h2 id="asa-drawer-title">Edit Permissions</h2><button aria-label="Close permissions" onClick={()=>dialog.current.close()}>×</button></div><div className="asa-person"><span className="as-avatar">{editing.person.name.split(" ").map(part=>part[0]).slice(0,2).join("")}</span><div><h3>{editing.person.name}</h3><p>{editing.person.email}</p><small>{editing.person.id}</small></div><span className="as-badge as-good">{editing.person.status}</span></div><div className="asa-tabs" role="tablist">{["Permissions","Profile","Activity Logs"].map(value=><button key={value} role="tab" aria-selected={tab===value} onClick={()=>setTab(value)}>{value}</button>)}</div>
      <div className="asa-tab-content">{tab==="Permissions"?<><h3>Module Access</h3><p>Select the modules this sub admin can access.</p><div className="asa-module-list">{operationalPermissions.map(([key,label],index)=><label key={key}><span className={`asa-module-icon as-tone-${index%6}`}><PublicIcon name={key==="publicWebsite"?"globe":key==="liveClasses"?"video":key==="certificates"?"award":"book"}/></span><span><strong>{label}</strong><small>{key==="publicWebsite"?"Allow access to public website management tools.":"Access this Learnova module."}</small></span><input className="asa-switch" type="checkbox" role="switch" checked={editing.draft[key]===true} onChange={event=>setEditing({...editing,draft:{...editing.draft,[key]:event.target.checked}})} aria-label={label}/></label>)}</div></>:tab==="Profile"?<dl>{[["Name",editing.person.name],["User ID",editing.person.id],["Email",editing.person.email],["Status",editing.person.status]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>:<p>View available frontend activity in <Link to="/admin/audit-logs" onClick={()=>dialog.current.close()}>Audit Logs</Link>.</p>}</div>
      {message&&<p role="status">{message}</p>}<footer className="asa-drawer-footer"><button onClick={()=>dialog.current.close()}>Cancel</button><button className="asa-save" onClick={save}>Save Changes</button></footer></>}</dialog>
  </div>;
}
